# Terraform Cheat Sheet 


#########
#init 
########
terraform init                  #First command to execute, installs Terraform moduels, a backend, provider plugins 
terraform init -input=false     #no inputs 
terraform init -backend-config=cfg/s3.dev.tf -reconfigure #Changes backend config, -reconfigure is used to tell Terraform don't copy existing state to the new remote state location 


########
#get 
#######
terraform get                   #Pulls modules into the .terraform dir 
terraform get -update=true      #Updates moduels 

########
#plan 
########
terraform plan                  #Scans all *.tf files in your dir and creates the plan 
terraform plan -out plan.out   #Out option is used to save the gnenerated plan to a file for later execution  


########
#apply 
########
terraform apply              
#Used to apply the changes required to reach the desired state of the configuration or desired 
#state of the pre-determined set of actions generated by a terraform plan
Usage: terraform apply [options] [dir-or-plan]

#########
#destroy 
#########

#########
#graph 
#########

#########
#validate 
#########

#########
#providers 
#########

#########
#state 
#########

###########
#workspaces 
###########

#########
#workspaces 
#########

